#!/bin/bash
shopt -s globstar
shopt -s nullglob

DIR="$(dirname "$(readlink -f "$0")")"

cd src
html_raw=$(grep -l --exclude='html/*' -- '' **/*.html **/*.htm)
mapfile -t html_files <<< "$html_raw"
css_files=(**/*.css)
js_files=(**/*.js)
cd ..

cores=$(grep -c ^processor /proc/cpuinfo)
echo "${css_files[@]}" | xargs -P "$cores" -n 1 "$DIR"/compile-css.sh
echo "${js_files[@]}" | xargs -P "$cores" -n 1 "$DIR"/compile-js.sh
echo "${html_files[@]}" | xargs -P "$cores" -n 1 "$DIR"/compile-html.sh

for file in "${css_files[@]}" "${js_files[@]}"; do
  "$DIR"/checksum-write.sh "src/$file"
  "$DIR"/checksum-write.sh "bin/$file"
done

for file in src/html/*; do
  "$DIR"/checksum-write.sh "$file"
done

rm -rf tmp
